// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sav.domain;

import com.sav.domain.ClientDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ClientIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ClientIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ClientIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ClientIntegrationTest: @Transactional;
    
    @Autowired
    private ClientDataOnDemand ClientIntegrationTest.dod;
    
    @Test
    public void ClientIntegrationTest.testCountClients() {
        org.junit.Assert.assertNotNull("Data on demand for 'Client' failed to initialize correctly", dod.getRandomClient());
        long count = com.sav.domain.Client.countClients();
        org.junit.Assert.assertTrue("Counter for 'Client' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ClientIntegrationTest.testFindClient() {
        com.sav.domain.Client obj = dod.getRandomClient();
        org.junit.Assert.assertNotNull("Data on demand for 'Client' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Client' failed to provide an identifier", id);
        obj = com.sav.domain.Client.findClient(id);
        org.junit.Assert.assertNotNull("Find method for 'Client' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Client' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ClientIntegrationTest.testFindAllClients() {
        org.junit.Assert.assertNotNull("Data on demand for 'Client' failed to initialize correctly", dod.getRandomClient());
        long count = com.sav.domain.Client.countClients();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Client', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.sav.domain.Client> result = com.sav.domain.Client.findAllClients();
        org.junit.Assert.assertNotNull("Find all method for 'Client' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Client' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ClientIntegrationTest.testFindClientEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Client' failed to initialize correctly", dod.getRandomClient());
        long count = com.sav.domain.Client.countClients();
        if (count > 20) count = 20;
        java.util.List<com.sav.domain.Client> result = com.sav.domain.Client.findClientEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Client' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Client' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ClientIntegrationTest.testFlush() {
        com.sav.domain.Client obj = dod.getRandomClient();
        org.junit.Assert.assertNotNull("Data on demand for 'Client' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Client' failed to provide an identifier", id);
        obj = com.sav.domain.Client.findClient(id);
        org.junit.Assert.assertNotNull("Find method for 'Client' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyClient(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Client' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClientIntegrationTest.testMerge() {
        com.sav.domain.Client obj = dod.getRandomClient();
        org.junit.Assert.assertNotNull("Data on demand for 'Client' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Client' failed to provide an identifier", id);
        obj = com.sav.domain.Client.findClient(id);
        boolean modified =  dod.modifyClient(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.sav.domain.Client merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Client' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClientIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Client' failed to initialize correctly", dod.getRandomClient());
        com.sav.domain.Client obj = dod.getNewTransientClient(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Client' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Client' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Client' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ClientIntegrationTest.testRemove() {
        com.sav.domain.Client obj = dod.getRandomClient();
        org.junit.Assert.assertNotNull("Data on demand for 'Client' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Client' failed to provide an identifier", id);
        obj = com.sav.domain.Client.findClient(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Client' with identifier '" + id + "'", com.sav.domain.Client.findClient(id));
    }
    
}
