// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sav.domain;

import com.sav.domain.LivraisonDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LivraisonIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LivraisonIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LivraisonIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: LivraisonIntegrationTest: @Transactional;
    
    @Autowired
    private LivraisonDataOnDemand LivraisonIntegrationTest.dod;
    
    @Test
    public void LivraisonIntegrationTest.testCountLivraisons() {
        org.junit.Assert.assertNotNull("Data on demand for 'Livraison' failed to initialize correctly", dod.getRandomLivraison());
        long count = com.sav.domain.Livraison.countLivraisons();
        org.junit.Assert.assertTrue("Counter for 'Livraison' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LivraisonIntegrationTest.testFindLivraison() {
        com.sav.domain.Livraison obj = dod.getRandomLivraison();
        org.junit.Assert.assertNotNull("Data on demand for 'Livraison' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Livraison' failed to provide an identifier", id);
        obj = com.sav.domain.Livraison.findLivraison(id);
        org.junit.Assert.assertNotNull("Find method for 'Livraison' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Livraison' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LivraisonIntegrationTest.testFindAllLivraisons() {
        org.junit.Assert.assertNotNull("Data on demand for 'Livraison' failed to initialize correctly", dod.getRandomLivraison());
        long count = com.sav.domain.Livraison.countLivraisons();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Livraison', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.sav.domain.Livraison> result = com.sav.domain.Livraison.findAllLivraisons();
        org.junit.Assert.assertNotNull("Find all method for 'Livraison' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Livraison' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LivraisonIntegrationTest.testFindLivraisonEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Livraison' failed to initialize correctly", dod.getRandomLivraison());
        long count = com.sav.domain.Livraison.countLivraisons();
        if (count > 20) count = 20;
        java.util.List<com.sav.domain.Livraison> result = com.sav.domain.Livraison.findLivraisonEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Livraison' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Livraison' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LivraisonIntegrationTest.testFlush() {
        com.sav.domain.Livraison obj = dod.getRandomLivraison();
        org.junit.Assert.assertNotNull("Data on demand for 'Livraison' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Livraison' failed to provide an identifier", id);
        obj = com.sav.domain.Livraison.findLivraison(id);
        org.junit.Assert.assertNotNull("Find method for 'Livraison' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLivraison(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Livraison' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LivraisonIntegrationTest.testMerge() {
        com.sav.domain.Livraison obj = dod.getRandomLivraison();
        org.junit.Assert.assertNotNull("Data on demand for 'Livraison' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Livraison' failed to provide an identifier", id);
        obj = com.sav.domain.Livraison.findLivraison(id);
        boolean modified =  dod.modifyLivraison(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.sav.domain.Livraison merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Livraison' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LivraisonIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Livraison' failed to initialize correctly", dod.getRandomLivraison());
        com.sav.domain.Livraison obj = dod.getNewTransientLivraison(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Livraison' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Livraison' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Livraison' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LivraisonIntegrationTest.testRemove() {
        com.sav.domain.Livraison obj = dod.getRandomLivraison();
        org.junit.Assert.assertNotNull("Data on demand for 'Livraison' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Livraison' failed to provide an identifier", id);
        obj = com.sav.domain.Livraison.findLivraison(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Livraison' with identifier '" + id + "'", com.sav.domain.Livraison.findLivraison(id));
    }
    
}
