// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sav.domain;

import com.sav.domain.MaterielRmaDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MaterielRmaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MaterielRmaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MaterielRmaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: MaterielRmaIntegrationTest: @Transactional;
    
    @Autowired
    private MaterielRmaDataOnDemand MaterielRmaIntegrationTest.dod;
    
    @Test
    public void MaterielRmaIntegrationTest.testCountMaterielRmas() {
        org.junit.Assert.assertNotNull("Data on demand for 'MaterielRma' failed to initialize correctly", dod.getRandomMaterielRma());
        long count = com.sav.domain.MaterielRma.countMaterielRmas();
        org.junit.Assert.assertTrue("Counter for 'MaterielRma' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MaterielRmaIntegrationTest.testFindMaterielRma() {
        com.sav.domain.MaterielRma obj = dod.getRandomMaterielRma();
        org.junit.Assert.assertNotNull("Data on demand for 'MaterielRma' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MaterielRma' failed to provide an identifier", id);
        obj = com.sav.domain.MaterielRma.findMaterielRma(id);
        org.junit.Assert.assertNotNull("Find method for 'MaterielRma' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'MaterielRma' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MaterielRmaIntegrationTest.testFindAllMaterielRmas() {
        org.junit.Assert.assertNotNull("Data on demand for 'MaterielRma' failed to initialize correctly", dod.getRandomMaterielRma());
        long count = com.sav.domain.MaterielRma.countMaterielRmas();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'MaterielRma', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.sav.domain.MaterielRma> result = com.sav.domain.MaterielRma.findAllMaterielRmas();
        org.junit.Assert.assertNotNull("Find all method for 'MaterielRma' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'MaterielRma' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MaterielRmaIntegrationTest.testFindMaterielRmaEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'MaterielRma' failed to initialize correctly", dod.getRandomMaterielRma());
        long count = com.sav.domain.MaterielRma.countMaterielRmas();
        if (count > 20) count = 20;
        java.util.List<com.sav.domain.MaterielRma> result = com.sav.domain.MaterielRma.findMaterielRmaEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'MaterielRma' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'MaterielRma' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MaterielRmaIntegrationTest.testFlush() {
        com.sav.domain.MaterielRma obj = dod.getRandomMaterielRma();
        org.junit.Assert.assertNotNull("Data on demand for 'MaterielRma' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MaterielRma' failed to provide an identifier", id);
        obj = com.sav.domain.MaterielRma.findMaterielRma(id);
        org.junit.Assert.assertNotNull("Find method for 'MaterielRma' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMaterielRma(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'MaterielRma' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MaterielRmaIntegrationTest.testMerge() {
        com.sav.domain.MaterielRma obj = dod.getRandomMaterielRma();
        org.junit.Assert.assertNotNull("Data on demand for 'MaterielRma' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MaterielRma' failed to provide an identifier", id);
        obj = com.sav.domain.MaterielRma.findMaterielRma(id);
        boolean modified =  dod.modifyMaterielRma(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.sav.domain.MaterielRma merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'MaterielRma' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MaterielRmaIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'MaterielRma' failed to initialize correctly", dod.getRandomMaterielRma());
        com.sav.domain.MaterielRma obj = dod.getNewTransientMaterielRma(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'MaterielRma' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'MaterielRma' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'MaterielRma' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MaterielRmaIntegrationTest.testRemove() {
        com.sav.domain.MaterielRma obj = dod.getRandomMaterielRma();
        org.junit.Assert.assertNotNull("Data on demand for 'MaterielRma' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MaterielRma' failed to provide an identifier", id);
        obj = com.sav.domain.MaterielRma.findMaterielRma(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'MaterielRma' with identifier '" + id + "'", com.sav.domain.MaterielRma.findMaterielRma(id));
    }
    
}
