// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sav.domain;

import com.sav.domain.PieceOffDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PieceOffIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PieceOffIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PieceOffIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PieceOffIntegrationTest: @Transactional;
    
    @Autowired
    private PieceOffDataOnDemand PieceOffIntegrationTest.dod;
    
    @Test
    public void PieceOffIntegrationTest.testCountPieceOffs() {
        org.junit.Assert.assertNotNull("Data on demand for 'PieceOff' failed to initialize correctly", dod.getRandomPieceOff());
        long count = com.sav.domain.PieceOff.countPieceOffs();
        org.junit.Assert.assertTrue("Counter for 'PieceOff' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PieceOffIntegrationTest.testFindPieceOff() {
        com.sav.domain.PieceOff obj = dod.getRandomPieceOff();
        org.junit.Assert.assertNotNull("Data on demand for 'PieceOff' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PieceOff' failed to provide an identifier", id);
        obj = com.sav.domain.PieceOff.findPieceOff(id);
        org.junit.Assert.assertNotNull("Find method for 'PieceOff' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'PieceOff' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PieceOffIntegrationTest.testFindAllPieceOffs() {
        org.junit.Assert.assertNotNull("Data on demand for 'PieceOff' failed to initialize correctly", dod.getRandomPieceOff());
        long count = com.sav.domain.PieceOff.countPieceOffs();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'PieceOff', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.sav.domain.PieceOff> result = com.sav.domain.PieceOff.findAllPieceOffs();
        org.junit.Assert.assertNotNull("Find all method for 'PieceOff' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'PieceOff' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PieceOffIntegrationTest.testFindPieceOffEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'PieceOff' failed to initialize correctly", dod.getRandomPieceOff());
        long count = com.sav.domain.PieceOff.countPieceOffs();
        if (count > 20) count = 20;
        java.util.List<com.sav.domain.PieceOff> result = com.sav.domain.PieceOff.findPieceOffEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'PieceOff' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'PieceOff' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PieceOffIntegrationTest.testFlush() {
        com.sav.domain.PieceOff obj = dod.getRandomPieceOff();
        org.junit.Assert.assertNotNull("Data on demand for 'PieceOff' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PieceOff' failed to provide an identifier", id);
        obj = com.sav.domain.PieceOff.findPieceOff(id);
        org.junit.Assert.assertNotNull("Find method for 'PieceOff' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPieceOff(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'PieceOff' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PieceOffIntegrationTest.testMerge() {
        com.sav.domain.PieceOff obj = dod.getRandomPieceOff();
        org.junit.Assert.assertNotNull("Data on demand for 'PieceOff' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PieceOff' failed to provide an identifier", id);
        obj = com.sav.domain.PieceOff.findPieceOff(id);
        boolean modified =  dod.modifyPieceOff(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.sav.domain.PieceOff merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'PieceOff' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PieceOffIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'PieceOff' failed to initialize correctly", dod.getRandomPieceOff());
        com.sav.domain.PieceOff obj = dod.getNewTransientPieceOff(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'PieceOff' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'PieceOff' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'PieceOff' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PieceOffIntegrationTest.testRemove() {
        com.sav.domain.PieceOff obj = dod.getRandomPieceOff();
        org.junit.Assert.assertNotNull("Data on demand for 'PieceOff' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PieceOff' failed to provide an identifier", id);
        obj = com.sav.domain.PieceOff.findPieceOff(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'PieceOff' with identifier '" + id + "'", com.sav.domain.PieceOff.findPieceOff(id));
    }
    
}
