// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sav.domain;

import com.sav.domain.ProduitDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProduitIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProduitIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProduitIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ProduitIntegrationTest: @Transactional;
    
    @Autowired
    private ProduitDataOnDemand ProduitIntegrationTest.dod;
    
    @Test
    public void ProduitIntegrationTest.testCountProduits() {
        org.junit.Assert.assertNotNull("Data on demand for 'Produit' failed to initialize correctly", dod.getRandomProduit());
        long count = com.sav.domain.Produit.countProduits();
        org.junit.Assert.assertTrue("Counter for 'Produit' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProduitIntegrationTest.testFindProduit() {
        com.sav.domain.Produit obj = dod.getRandomProduit();
        org.junit.Assert.assertNotNull("Data on demand for 'Produit' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Produit' failed to provide an identifier", id);
        obj = com.sav.domain.Produit.findProduit(id);
        org.junit.Assert.assertNotNull("Find method for 'Produit' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Produit' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProduitIntegrationTest.testFindAllProduits() {
        org.junit.Assert.assertNotNull("Data on demand for 'Produit' failed to initialize correctly", dod.getRandomProduit());
        long count = com.sav.domain.Produit.countProduits();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Produit', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.sav.domain.Produit> result = com.sav.domain.Produit.findAllProduits();
        org.junit.Assert.assertNotNull("Find all method for 'Produit' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Produit' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProduitIntegrationTest.testFindProduitEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Produit' failed to initialize correctly", dod.getRandomProduit());
        long count = com.sav.domain.Produit.countProduits();
        if (count > 20) count = 20;
        java.util.List<com.sav.domain.Produit> result = com.sav.domain.Produit.findProduitEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Produit' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Produit' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProduitIntegrationTest.testFlush() {
        com.sav.domain.Produit obj = dod.getRandomProduit();
        org.junit.Assert.assertNotNull("Data on demand for 'Produit' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Produit' failed to provide an identifier", id);
        obj = com.sav.domain.Produit.findProduit(id);
        org.junit.Assert.assertNotNull("Find method for 'Produit' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProduit(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Produit' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProduitIntegrationTest.testMerge() {
        com.sav.domain.Produit obj = dod.getRandomProduit();
        org.junit.Assert.assertNotNull("Data on demand for 'Produit' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Produit' failed to provide an identifier", id);
        obj = com.sav.domain.Produit.findProduit(id);
        boolean modified =  dod.modifyProduit(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.sav.domain.Produit merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Produit' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProduitIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Produit' failed to initialize correctly", dod.getRandomProduit());
        com.sav.domain.Produit obj = dod.getNewTransientProduit(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Produit' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Produit' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Produit' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProduitIntegrationTest.testRemove() {
        com.sav.domain.Produit obj = dod.getRandomProduit();
        org.junit.Assert.assertNotNull("Data on demand for 'Produit' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Produit' failed to provide an identifier", id);
        obj = com.sav.domain.Produit.findProduit(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Produit' with identifier '" + id + "'", com.sav.domain.Produit.findProduit(id));
    }
    
}
