// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sav.domain;

import com.sav.domain.Produit;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ProduitDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProduitDataOnDemand: @Component;
    
    private Random ProduitDataOnDemand.rnd = new SecureRandom();
    
    private List<Produit> ProduitDataOnDemand.data;
    
    public Produit ProduitDataOnDemand.getNewTransientProduit(int index) {
        Produit obj = new Produit();
        setCodeArticle(obj, index);
        setModele(obj, index);
        return obj;
    }
    
    public void ProduitDataOnDemand.setCodeArticle(Produit obj, int index) {
        String codeArticle = "codeArticle_" + index;
        obj.setCodeArticle(codeArticle);
    }
    
    public void ProduitDataOnDemand.setModele(Produit obj, int index) {
        String modele = "modele_" + index;
        obj.setModele(modele);
    }
    
    public Produit ProduitDataOnDemand.getSpecificProduit(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Produit obj = data.get(index);
        return Produit.findProduit(obj.getId());
    }
    
    public Produit ProduitDataOnDemand.getRandomProduit() {
        init();
        Produit obj = data.get(rnd.nextInt(data.size()));
        return Produit.findProduit(obj.getId());
    }
    
    public boolean ProduitDataOnDemand.modifyProduit(Produit obj) {
        return false;
    }
    
    public void ProduitDataOnDemand.init() {
        data = Produit.findProduitEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Produit' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.sav.domain.Produit>();
        for (int i = 0; i < 10; i++) {
            Produit obj = getNewTransientProduit(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
