// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sav.domain;

import com.sav.domain.AdressRetour;
import com.sav.domain.AdressRetourDataOnDemand;
import com.sav.domain.Client;
import com.sav.domain.ClientDataOnDemand;
import com.sav.domain.Rma;
import com.sav.reference.Transport;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect RmaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RmaDataOnDemand: @Component;
    
    private Random RmaDataOnDemand.rnd = new SecureRandom();
    
    private List<Rma> RmaDataOnDemand.data;
    
    @Autowired
    private AdressRetourDataOnDemand RmaDataOnDemand.adressRetourDataOnDemand;
    
    @Autowired
    private ClientDataOnDemand RmaDataOnDemand.clientDataOnDemand;
    
    public Rma RmaDataOnDemand.getNewTransientRma(int index) {
        Rma obj = new Rma();
        setAdresseDeRetour(obj, index);
        setClient(obj, index);
        setCreeePar(obj, index);
        setDateCreation(obj, index);
        setRmaNumber(obj, index);
        setSociete(obj, index);
        setTransport(obj, index);
        return obj;
    }
    
    public void RmaDataOnDemand.setAdresseDeRetour(Rma obj, int index) {
        AdressRetour adresseDeRetour = adressRetourDataOnDemand.getRandomAdressRetour();
        obj.setAdresseDeRetour(adresseDeRetour);
    }
    
    public void RmaDataOnDemand.setClient(Rma obj, int index) {
        Client client = clientDataOnDemand.getRandomClient();
        obj.setClient(client);
    }
    
    public void RmaDataOnDemand.setCreeePar(Rma obj, int index) {
        String creeePar = "creeePar_" + index;
        obj.setCreeePar(creeePar);
    }
    
    public void RmaDataOnDemand.setDateCreation(Rma obj, int index) {
        Date dateCreation = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateCreation(dateCreation);
    }
    
    public void RmaDataOnDemand.setRmaNumber(Rma obj, int index) {
        String rmaNumber = "rmaNumber_" + index;
        obj.setRmaNumber(rmaNumber);
    }
    
    public void RmaDataOnDemand.setSociete(Rma obj, int index) {
        String societe = "societe_" + index;
        obj.setSociete(societe);
    }
    
    public void RmaDataOnDemand.setTransport(Rma obj, int index) {
        Transport transport = Transport.class.getEnumConstants()[0];
        obj.setTransport(transport);
    }
    
    public Rma RmaDataOnDemand.getSpecificRma(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Rma obj = data.get(index);
        return Rma.findRma(obj.getId());
    }
    
    public Rma RmaDataOnDemand.getRandomRma() {
        init();
        Rma obj = data.get(rnd.nextInt(data.size()));
        return Rma.findRma(obj.getId());
    }
    
    public boolean RmaDataOnDemand.modifyRma(Rma obj) {
        return false;
    }
    
    public void RmaDataOnDemand.init() {
        data = Rma.findRmaEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Rma' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.sav.domain.Rma>();
        for (int i = 0; i < 10; i++) {
            Rma obj = getNewTransientRma(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
