// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sav.domain;

import com.sav.domain.RmaDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RmaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RmaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RmaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: RmaIntegrationTest: @Transactional;
    
    @Autowired
    private RmaDataOnDemand RmaIntegrationTest.dod;
    
    @Test
    public void RmaIntegrationTest.testCountRmas() {
        org.junit.Assert.assertNotNull("Data on demand for 'Rma' failed to initialize correctly", dod.getRandomRma());
        long count = com.sav.domain.Rma.countRmas();
        org.junit.Assert.assertTrue("Counter for 'Rma' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RmaIntegrationTest.testFindRma() {
        com.sav.domain.Rma obj = dod.getRandomRma();
        org.junit.Assert.assertNotNull("Data on demand for 'Rma' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Rma' failed to provide an identifier", id);
        obj = com.sav.domain.Rma.findRma(id);
        org.junit.Assert.assertNotNull("Find method for 'Rma' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Rma' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RmaIntegrationTest.testFindAllRmas() {
        org.junit.Assert.assertNotNull("Data on demand for 'Rma' failed to initialize correctly", dod.getRandomRma());
        long count = com.sav.domain.Rma.countRmas();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Rma', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.sav.domain.Rma> result = com.sav.domain.Rma.findAllRmas();
        org.junit.Assert.assertNotNull("Find all method for 'Rma' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Rma' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RmaIntegrationTest.testFindRmaEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Rma' failed to initialize correctly", dod.getRandomRma());
        long count = com.sav.domain.Rma.countRmas();
        if (count > 20) count = 20;
        java.util.List<com.sav.domain.Rma> result = com.sav.domain.Rma.findRmaEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Rma' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Rma' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RmaIntegrationTest.testFlush() {
        com.sav.domain.Rma obj = dod.getRandomRma();
        org.junit.Assert.assertNotNull("Data on demand for 'Rma' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Rma' failed to provide an identifier", id);
        obj = com.sav.domain.Rma.findRma(id);
        org.junit.Assert.assertNotNull("Find method for 'Rma' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRma(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Rma' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RmaIntegrationTest.testMerge() {
        com.sav.domain.Rma obj = dod.getRandomRma();
        org.junit.Assert.assertNotNull("Data on demand for 'Rma' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Rma' failed to provide an identifier", id);
        obj = com.sav.domain.Rma.findRma(id);
        boolean modified =  dod.modifyRma(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.sav.domain.Rma merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Rma' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RmaIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Rma' failed to initialize correctly", dod.getRandomRma());
        com.sav.domain.Rma obj = dod.getNewTransientRma(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Rma' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Rma' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Rma' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RmaIntegrationTest.testRemove() {
        com.sav.domain.Rma obj = dod.getRandomRma();
        org.junit.Assert.assertNotNull("Data on demand for 'Rma' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Rma' failed to provide an identifier", id);
        obj = com.sav.domain.Rma.findRma(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Rma' with identifier '" + id + "'", com.sav.domain.Rma.findRma(id));
    }
    
}
